plane:
- MANUAL
- CIRCLE
- STABILIZE
- TRAINING
- ACRO
- FBWA
- FBWB
- CRUISE
- AUTOTUNE
- AUTO
- RTL
- LOITER
- LAND
- GUIDED
- INITIALISING
copter:
- STABILIZE
- ACRO
- ALT_HOLD
- AUTO
- GUIDED
- LOITER
- RTL
- CIRCLE
- POSITION
- LAND
- OF_LOITER
- DRIFT
- SPORT
- FLIP
- AUTOTUNE
- POSHOLD
rover:
- MANUAL
- LEARNING
- STEERING
- HOLD
- AUTO
- RTL
- GUIDED
- INITIALISING
